In [1]:
import numpy as np

In [2]:
array1 = np.array(range(30))
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
array2 = array1.reshape((5,6))
array2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [15]:
array3 = array2.copy()
for i in range(len(array3)):
    for j in range (len(array3[0])):
        if (array3[i][j] %6 != 1):
            array3[i][j] = 0
      
array3

array([[ 0,  1,  0,  0,  0,  0],
       [ 0,  7,  0,  0,  0,  0],
       [ 0, 13,  0,  0,  0,  0],
       [ 0, 19,  0,  0,  0,  0],
       [ 0, 25,  0,  0,  0,  0]])

In [17]:
array4 = np.where(array3 % 6 == 1, "Y", "N")
array4

array([['N', 'Y', 'N', 'N', 'N', 'N'],
       ['N', 'Y', 'N', 'N', 'N', 'N'],
       ['N', 'Y', 'N', 'N', 'N', 'N'],
       ['N', 'Y', 'N', 'N', 'N', 'N'],
       ['N', 'Y', 'N', 'N', 'N', 'N']], dtype='<U1')