In [1]:
import numpy as np

In [2]:
array1 = np.array([[10, 8], [3, 5]])
array1

array([[10,  8],
       [ 3,  5]])

In [8]:
inv_arr = np.linalg.inv(array1)
print("inverse of original array = ")
print(inv_arr)

unit_arr = np.dot(array1, inv_arr)
print("dot of original array and inverse array = ")
print(unit_arr)

inverse of original array = 
[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
dot of original array and inverse array = 
[[1. 0.]
 [0. 1.]]


In [10]:
w, v = np.linalg.eig(array1)
print("eigen value = ")
print(w)
print("eigen vector = ")
print(v)

eigen value = 
[13.  2.]
eigen vector = 
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [17]:
a, b, c = np.linalg.svd(array1)
print(a)
print(b)
print(c)

[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]
[13.94721714  1.86417116]
[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
