In [1]:
import numpy as np

In [2]:
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 

In [3]:
print('b list: ', list(b))
print('b tolist', b.tolist())

b list:  [array([1, 2, 1, 1]), array([8, 5, 0, 5]), array([2, 9, 0, 0])]
b tolist [[1, 2, 1, 1], [8, 5, 0, 5], [2, 9, 0, 0]]


lsit會把每一層分別轉換成 List

tolist()會將全部一次轉乘list

In [4]:
print(a)
print("a dimention :", a.ndim)
print("a shape :", a.shape)
print("a size :", a.size)
print("a type :", a.dtype)
print("a item size :",a.itemsize)
print("a length :", len(a))
print("a type :", type(a))

[5 1 0 7 5 2]
a dimention : 1
a shape : (6,)
a size : 6
a type : int32
a item size : 4
a length : 6
a type : <class 'numpy.ndarray'>


In [5]:
print(b)
print("b dimention :", b.ndim)
print("b shape :", b.shape)
print("b size :", b.size)
print("b type :", b.dtype)
print("b item size :",b.itemsize)
print("b length :", len(b))
print("b type :", type(b))

[[1 2 1 1]
 [8 5 0 5]
 [2 9 0 0]]
b dimention : 2
b shape : (3, 4)
b size : 12
b type : int32
b item size : 4
b length : 3
b type : <class 'numpy.ndarray'>


In [6]:
print(c)
print("c dimention :", c.ndim)
print("c shape :", c.shape)
print("c size :", c.size)
print("c type :", c.dtype)
print("c item size :",c.itemsize)
print("c length :", len(c))
print("c type :", type(c))

[[[5 2]
  [6 4]
  [1 3]]

 [[0 7]
  [6 2]
  [9 7]]]
c dimention : 3
c shape : (2, 3, 2)
c size : 12
c type : int32
c item size : 4
c length : 2
c type : <class 'numpy.ndarray'>


In [9]:
def to_list(num):
    if type(num) != np.ndarray:
        return num
    return [to_list(i) for i in num]

print(to_list(c))

[[[5, 2], [6, 4], [1, 3]], [[0, 7], [6, 2], [9, 7]]]
