In [1]:
import numpy as np

In [4]:
print(np.zeros((2, 3)))
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


empty是很小的值，不是0

In [11]:
a = np.random.rand(2, 3)
print((a*100).round())

[[44.  1. 22.]
 [34. 36. 93.]]


In [15]:
m = 50
n = 0

a = (np.random.rand(2, 3) * (m - n)).round()
a

array([[24., 38., 11.],
       [15., 32., 45.]])