In [1]:
import numpy as np

In [4]:
print(np.zeros((2, 3)))
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


empty是很小的值，不是0

In [11]:
a = np.random.rand(2, 3)
print((a*100).round())

[[44.  1. 22.]
 [34. 36. 93.]]


In [12]:
m = 50
n = 0

a = np.random.rand(2, 3) * (m - n)


array([[ 0.98379615,  7.72337082, 31.88722342],
       [49.90476631, 48.43699908, 35.29639353]])