In [1]:
import numpy as np

In [2]:
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

In [4]:
print(a + a)
print(a + b)
print(a + c)
print(a + d)
#print(a + e)

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


a + e 因為其dimention不一樣，故不能直接疊加，a + d雖然不一樣，但是是為每個元素都加

In [5]:
A = np.ones(3)*1
B = np.ones(3)*2

In [7]:
(A+B) * (-A / 2)

array([-1.5, -1.5, -1.5])

In [9]:
ans = []
for i in range(len(A)):
    func = (A[i] + B[i]) * (-A[i] / 2)
    ans.append(func)
ans

[-1.5, -1.5, -1.5]

In [10]:
A = np.ones((1,6))
B = np.ones((6,1))

In [11]:
A * B

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
A @ B

array([[6.]])