In [1]:
import numpy as np

In [7]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
a[2:6] = -1 * a[2:6]
a

array([ 0,  1, -2, -3, -4, -5,  6,  7,  8,  9, 10])

In [11]:
b = np.random.rand(3, 6)
b

array([[0.06535256, 0.35763107, 0.25318481, 0.39809831, 0.47902463,
        0.09917489],
       [0.17743953, 0.40588235, 0.93602331, 0.49369654, 0.36344688,
        0.44809711],
       [0.90062128, 0.79685564, 0.12113445, 0.9978754 , 0.68426689,
        0.84779014]])

In [12]:
count = 0
for i in range(len(b)):
    for j in range(len(b[0])):
        if b[i][j] > 0.5:
            count += 1
            
count

6

In [13]:
len(b[b > 0.5])

6