In [1]:
import numpy as np

In [3]:
a = np.arange(6)

print(a.sum()) 
print(np.sum(a))
print(sum(a)) 

15
15
15


In [4]:
A = np.random.random((5, 5))
A

array([[0.54052509, 0.03064154, 0.58398054, 0.31133965, 0.74315701],
       [0.90758932, 0.96824203, 0.50433178, 0.93063103, 0.79707694],
       [0.70613321, 0.5901196 , 0.68162261, 0.52609137, 0.15702346],
       [0.67004659, 0.93618959, 0.4476724 , 0.48755647, 0.7072566 ],
       [0.70363084, 0.10049487, 0.35408606, 0.02894126, 0.40695697]])

In [5]:
A = (A  - np.mean(A)) / np.std(A)
A

array([[-0.04553192, -1.92866439,  0.11496036, -0.89197332,  0.70284044],
       [ 1.3101317 ,  1.53413792, -0.17920322,  1.39523069,  0.90198072],
       [ 0.56610191,  0.13763349,  0.4755779 , -0.09883942, -1.46190313],
       [ 0.43282464,  1.4157599 , -0.38846105, -0.2411588 ,  0.57025088],
       [ 0.55685999, -1.67067791, -0.73409973, -1.93494397, -0.5388337 ]])

In [7]:
B = np.random.rand(10)
B

array([0.81850637, 0.73753802, 0.46359568, 0.28672527, 0.82244369,
       0.30359602, 0.44362486, 0.90196811, 0.77447994, 0.36436452])

In [8]:
B[B.argmax()] = -1
B

array([ 0.81850637,  0.73753802,  0.46359568,  0.28672527,  0.82244369,
        0.30359602,  0.44362486, -1.        ,  0.77447994,  0.36436452])