In [1]:
import numpy as np

In [9]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
Z

array([[[4, 0, 6, ..., 3, 8, 7],
        [5, 4, 3, ..., 3, 1, 7],
        [2, 4, 3, ..., 0, 0, 8],
        ...,
        [4, 5, 6, ..., 7, 9, 8],
        [2, 7, 4, ..., 0, 6, 0],
        [7, 1, 2, ..., 7, 9, 2]],

       [[4, 7, 9, ..., 5, 0, 0],
        [0, 4, 1, ..., 0, 8, 8],
        [4, 6, 9, ..., 0, 6, 8],
        ...,
        [4, 1, 2, ..., 2, 2, 4],
        [9, 1, 2, ..., 2, 8, 6],
        [2, 5, 5, ..., 1, 2, 3]],

       [[1, 5, 4, ..., 2, 1, 4],
        [7, 0, 5, ..., 9, 9, 9],
        [0, 9, 7, ..., 3, 1, 0],
        ...,
        [1, 2, 5, ..., 2, 1, 6],
        [3, 7, 1, ..., 5, 3, 3],
        [9, 2, 8, ..., 2, 7, 0]],

       ...,

       [[5, 8, 2, ..., 9, 6, 6],
        [3, 4, 9, ..., 5, 6, 3],
        [3, 9, 6, ..., 4, 4, 3],
        ...,
        [0, 8, 8, ..., 9, 3, 9],
        [5, 6, 2, ..., 6, 7, 2],
        [4, 8, 9, ..., 9, 7, 5]],

       [[7, 2, 7, ..., 1, 0, 4],
        [1, 8, 2, ..., 6, 8, 7],
        [5, 7, 0, ..., 5, 5, 5],
        ...,
        [4, 4, 2, ..., 

In [10]:
%timeit -n 10 a = 2
Z_new1 = []

for i in np.nditer(Z):
    Z_new1.append(i + 1)
    
np.array(Z).reshape(100, 100, 100)

31.4 ns ± 8.33 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[4, 0, 6, ..., 3, 8, 7],
        [5, 4, 3, ..., 3, 1, 7],
        [2, 4, 3, ..., 0, 0, 8],
        ...,
        [4, 5, 6, ..., 7, 9, 8],
        [2, 7, 4, ..., 0, 6, 0],
        [7, 1, 2, ..., 7, 9, 2]],

       [[4, 7, 9, ..., 5, 0, 0],
        [0, 4, 1, ..., 0, 8, 8],
        [4, 6, 9, ..., 0, 6, 8],
        ...,
        [4, 1, 2, ..., 2, 2, 4],
        [9, 1, 2, ..., 2, 8, 6],
        [2, 5, 5, ..., 1, 2, 3]],

       [[1, 5, 4, ..., 2, 1, 4],
        [7, 0, 5, ..., 9, 9, 9],
        [0, 9, 7, ..., 3, 1, 0],
        ...,
        [1, 2, 5, ..., 2, 1, 6],
        [3, 7, 1, ..., 5, 3, 3],
        [9, 2, 8, ..., 2, 7, 0]],

       ...,

       [[5, 8, 2, ..., 9, 6, 6],
        [3, 4, 9, ..., 5, 6, 3],
        [3, 9, 6, ..., 4, 4, 3],
        ...,
        [0, 8, 8, ..., 9, 3, 9],
        [5, 6, 2, ..., 6, 7, 2],
        [4, 8, 9, ..., 9, 7, 5]],

       [[7, 2, 7, ..., 1, 0, 4],
        [1, 8, 2, ..., 6, 8, 7],
        [5, 7, 0, ..., 5, 5, 5],
        ...,
        [4, 4, 2, ..., 

In [12]:
%timeit -n 10 a = 2
Z_nwe2 = np.add(Z,1)
Z_nwe2

34.3 ns ± 19.2 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[ 5,  1,  7, ...,  4,  9,  8],
        [ 6,  5,  4, ...,  4,  2,  8],
        [ 3,  5,  4, ...,  1,  1,  9],
        ...,
        [ 5,  6,  7, ...,  8, 10,  9],
        [ 3,  8,  5, ...,  1,  7,  1],
        [ 8,  2,  3, ...,  8, 10,  3]],

       [[ 5,  8, 10, ...,  6,  1,  1],
        [ 1,  5,  2, ...,  1,  9,  9],
        [ 5,  7, 10, ...,  1,  7,  9],
        ...,
        [ 5,  2,  3, ...,  3,  3,  5],
        [10,  2,  3, ...,  3,  9,  7],
        [ 3,  6,  6, ...,  2,  3,  4]],

       [[ 2,  6,  5, ...,  3,  2,  5],
        [ 8,  1,  6, ..., 10, 10, 10],
        [ 1, 10,  8, ...,  4,  2,  1],
        ...,
        [ 2,  3,  6, ...,  3,  2,  7],
        [ 4,  8,  2, ...,  6,  4,  4],
        [10,  3,  9, ...,  3,  8,  1]],

       ...,

       [[ 6,  9,  3, ..., 10,  7,  7],
        [ 4,  5, 10, ...,  6,  7,  4],
        [ 4, 10,  7, ...,  5,  5,  4],
        ...,
        [ 1,  9,  9, ..., 10,  4, 10],
        [ 6,  7,  3, ...,  7,  8,  3],
        [ 5,  9, 10, ..., 10,  8

In [13]:
Z = np.random.randint(0, 10, 50)
Z

array([8, 5, 8, 0, 1, 2, 8, 5, 6, 3, 1, 7, 4, 9, 0, 0, 8, 5, 8, 3, 9, 3,
       3, 9, 3, 5, 9, 7, 2, 6, 4, 4, 9, 3, 6, 2, 1, 4, 5, 6, 8, 0, 6, 3,
       9, 6, 8, 7, 7, 8])

In [20]:

counter_list=[]

for i in range(10):
    counter = 0
    for j in Z:
        if j==i:
            counter+=1
    counter_list.append(counter)
    
counter_list.index(max(counter_list))

8

In [21]:
index_list = []
for i in range(len(Z)):
    if Z[i] == counter_list.index(max(counter_list)):
        index_list.append(i)
        
index_list

[0, 2, 6, 16, 18, 40, 46, 49]

In [22]:

a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))

[1, 6, 6, 3, 7, 7]
[1, 6, 6, 3, 7, 7]
[[5, 5, 4, 2], [7, 3, 7, 6], [4, 4, 3, 7]]
[array([5, 5, 4, 2]), array([7, 3, 7, 6]), array([4, 4, 3, 7])]
[[[3, 0], [4, 9], [0, 2]], [[7, 1], [7, 1], [8, 4]]]
[array([[3, 0],
       [4, 9],
       [0, 2]]), array([[7, 1],
       [7, 1],
       [8, 4]])]


In [28]:
def to_list(A):
    if type(A) != np.ndarray:
        return A
    new_list = []
    for i in A:
        new_list.append(to_list(i))
        
    return new_list
to_list(b)

[[5, 5, 4, 2], [7, 3, 7, 6], [4, 4, 3, 7]]